work_dir: /data/wangkun/project/work_dir/LowQSAR/stgcn/ntu60/cs-stgcn-bs64

# feeder
feeder: feeder.feeder_skeleton.Feeder
train_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu/preprocessed_NTU60_CS.npz
  dataset: 'ntu'
  split: train
  window_size: 64
  random_shear: 0.3
  resize_crop: True
  p_interval: [0.5, 1]
  get_pairs: False
  preprocess: False
#  mini: 10

#  backup: True
#  debug: True
test_feeder_args:
  data_path: /data/wangkun/project/datasets/NTU_dataset/ntu/preprocessed_NTU60_CS.npz
  dataset: 'ntu'
  split: test
  window_size: 64
  resize_crop: True
  p_interval: [0.95]
  preprocess: False
#  mini: 10


# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu'
    strategy: 'spatial'
  base_channel: 64
  output_channel: 256
  return_ft: False
#  mini: True


weight_decay: 0.0001
base_lr: 0.001
optimizer: 'Adam'
lr_decay_type: 'cosine'
end_cosine_lr: 0.0001
device: [0]
batch_size: 64
test_batch_size: 32
num_epoch: 80
warmup_epoch: 5
seed: -1
eval_interval: 5
save_interval: 50
bool_save_model: False
bool_save_checkpoint: False