work_dir: /data/wangkun/project/work_dir/LowQSAR/HCN/pku51/cs-1108-sgd
#weights: /data/wangkun/project/work_dir/CrossDt/HCN/pkummd_cs/0909-exp-v7/best_model.pt
#phase: 'extract_feature'

# feeder
feeder: feeder.feeder_skeleton.Feeder
train_feeder_args:
  data_path: /data/wangkun/project/datasets/PKUMMD/pku_part1/preprocessed_N51_CS.npz
  dataset: 'pkummd'
  split: train
  window_size: 64
  random_rot: False
  random_shear: 0.3
  resize_crop: True
  random_crop: False
  p_interval: [0.5, 1]
  vel: False
  bone: False
  coordinate_transfer_type: 888
  normalization: -1
  vertical: True
  fixed_direction: True
  padding_none: True
  preprocess: False
test_feeder_args:
  data_path: /data/wangkun/project/datasets/PKUMMD/pku_part1/preprocessed_N51_CS.npz
  dataset: 'pkummd'
  split: test
  resize_crop: True
  random_crop: False
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  coordinate_transfer_type: 888
  normalization: -1
  vertical: True
  fixed_direction: True
  padding_none: True
  preprocess: False

# model
model: net.HCN.Model
model_args:
  in_channel: 3
  num_joint: 25
  num_person: 2
  num_class: 51
  out_channel: 128
  window_size: 64

weight_decay: 0.0001
#base_lr: 0.001
base_lr: 0.1
#optimizer: 'Adam'
optimizer: 'SGD'
lr_decay_type: 'cosine'
#end_cosine_lr: 0.0001
end_cosine_lr: 0.01
device: [0]
batch_size: 128
test_batch_size: 32
num_epoch: 80
#warmup_epoch: 10
seed: -1
eval_interval: 5
save_interval: 50
bool_save_model: False
bool_save_checkpoint: False